version: '2'
services:
    db:
        image: 'mysql:5.7'
        ports:
            - '3306:3306'
        volumes:
            - ./docker/data/db:/var/lib/mysql
        environment:
            MYSQL_DATABASE: sphinx
            MYSQL_USER: sphinx
            MYSQL_PASSWORD: sphinx
            MYSQL_ROOT_PASSWORD: sphinx
#        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    app:
        build: ./docker/app
        depends_on:
            - db
        volumes:
            - .:/var/www/sphinx
            - ./docker/logs/sphinx:/var/www/sphinx/var/log
    nginx:
        build: ./docker/nginx
        ports:
            - '80:80'
        depends_on:
            - app
        volumes_from:
            - app
        volumes:
            - ./docker/logs/nginx/:/var/log/nginx
    elasticsearch:
        build: ./docker/elasticsearch
        volumes:
            - ./docker/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
            - ./docker/data/elasticsearch:/usr/share/elasticsearch/data
        ports:
            - '9200:9200'
            - '9300:9300'
        environment:
            ES_JAVA_OPTS: '-Xmx256m -Xms256m'
    kibana:
        build: ./docker/kibana
        volumes:
            - ./docker/kibana/config/:/usr/share/kibana/config:ro
        ports:
            - '5601:5601'
        depends_on:
            - elasticsearch